version: '3'
services:
  db-postgresql:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${MONOLITH_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${MONOLITH_DATABASE_PASSWORD}
    ports:
      - "7432:5432"
  web:
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - MONOLITH_DATABASE_PORT=${MONOLITH_DATABASE_PORT}
      # - If the MONOLITH_DATABASE_URL is used, the USERNAME, PASSWORD and HOST are optional.
      - MONOLITH_DATABASE_URL=${MONOLITH_DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - MONOLITH_DATABASE_USERNAME=${MONOLITH_DATABASE_USERNAME}
      - MONOLITH_DATABASE_PASSWORD=${MONOLITH_DATABASE_PASSWORD}
    volumes:
      - web-storage:/rails/storage
    depends_on:
      - db-postgresql
    ports:
      - "3000:3000"

volumes:
  postgres-data: {}
  web-storage: {}
