INDONESIAN_AREAS = [
  {code: "31", name: "DKI JAKARTA", area_type: "PROVINCE"},
  {code: "31.01", name: "KAB. ADM. KEP. SERIBU", area_type: "CITY"},
  {code: "31.71", name: "KOTA ADM. JAKARTA PUSAT", area_type: "CITY"},
  {code: "31.72", name: "KOTA ADM. JAKARTA UTARA", area_type: "CITY"},
  {code: "31.73", name: "KOTA ADM. JAKARTA BARAT", area_type: "CITY"},
  {code: "31.74", name: "KOTA ADM. JAKARTA SELATAN", area_type: "CITY"},
  {code: "31.75", name: "KOTA ADM. JAKARTA TIMUR", area_type: "CITY"},
  {code: "32", name: "JAWA BARAT", area_type: "PROVINCE"},
  {code: "32.01", name: "KAB. BOGOR", area_type: "CITY"},
  {code: "32.02", name: "KAB. SUKABUMI", area_type: "CITY"},
  {code: "32.03", name: "KAB. CIANJUR", area_type: "CITY"},
  {code: "32.04", name: "KAB. BANDUNG", area_type: "CITY"},
  {code: "32.05", name: "KAB. GARUT", area_type: "CITY"},
  {code: "32.06", name: "KAB. TASIKMALAYA", area_type: "CITY"},
  {code: "32.07", name: "KAB. CIAMIS", area_type: "CITY"},
  {code: "32.08", name: "KAB. KUNINGAN", area_type: "CITY"},
  {code: "32.09", name: "KAB. CIREBON", area_type: "CITY"},
  {code: "32.10", name: "KAB. MAJALENGKA", area_type: "CITY"},
  {code: "32.11", name: "KAB. SUMEDANG", area_type: "CITY"},
  {code: "32.12", name: "KAB. INDRAMAYU", area_type: "CITY"},
  {code: "32.13", name: "KAB. SUBANG", area_type: "CITY"},
  {code: "32.14", name: "KAB. PURWAKARTA", area_type: "CITY"},
  {code: "32.15", name: "KAB. KARAWANG", area_type: "CITY"},
  {code: "32.16", name: "KAB. BEKASI", area_type: "CITY"},
  {code: "32.17", name: "KAB. BANDUNG BARAT", area_type: "CITY"},
  {code: "32.18", name: "KAB. PANGANDARAN", area_type: "CITY"},
  {code: "32.71", name: "KOTA BOGOR", area_type: "CITY"},
  {code: "32.72", name: "KOTA SUKABUMI", area_type: "CITY"},
  {code: "32.73", name: "KOTA BANDUNG", area_type: "CITY"},
  {code: "32.74", name: "KOTA CIREBON", area_type: "CITY"},
  {code: "32.75", name: "KOTA BEKASI", area_type: "CITY"},
  {code: "32.76", name: "KOTA DEPOK", area_type: "CITY"},
  {code: "32.77", name: "KOTA CIMAHI", area_type: "CITY"},
  {code: "32.78", name: "KOTA TASIKMALAYA", area_type: "CITY"},
  {code: "32.79", name: "KOTA BANJAR", area_type: "CITY"},
  {code: "33", name: "JAWA TENGAH", area_type: "PROVINCE"},
  {code: "33.01", name: "KAB. CILACAP", area_type: "CITY"},
  {code: "33.02", name: "KAB. BANYUMAS", area_type: "CITY"},
  {code: "33.03", name: "KAB. PURBALINGGA", area_type: "CITY"},
  {code: "33.04", name: "KAB. BANJARNEGARA", area_type: "CITY"},
  {code: "33.05", name: "KAB. KEBUMEN", area_type: "CITY"},
  {code: "33.06", name: "KAB. PURWOREJO", area_type: "CITY"},
  {code: "33.07", name: "KAB. WONOSOBO", area_type: "CITY"},
  {code: "33.08", name: "KAB. MAGELANG", area_type: "CITY"},
  {code: "33.09", name: "KAB. BOYOLALI", area_type: "CITY"},
  {code: "33.10", name: "KAB. KLATEN", area_type: "CITY"},
  {code: "33.11", name: "KAB. SUKOHARJO", area_type: "CITY"},
  {code: "33.12", name: "KAB. WONOGIRI", area_type: "CITY"},
  {code: "33.13", name: "KAB. KARANGANYAR", area_type: "CITY"},
  {code: "33.14", name: "KAB. SRAGEN", area_type: "CITY"},
  {code: "33.15", name: "KAB. GROBOGAN", area_type: "CITY"},
  {code: "33.16", name: "KAB. BLORA", area_type: "CITY"},
  {code: "33.17", name: "KAB. REMBANG", area_type: "CITY"},
  {code: "33.18", name: "KAB. PATI", area_type: "CITY"},
  {code: "33.19", name: "KAB. KUDUS", area_type: "CITY"},
  {code: "33.20", name: "KAB. JEPARA", area_type: "CITY"},
  {code: "33.21", name: "KAB. DEMAK", area_type: "CITY"},
  {code: "33.22", name: "KAB. SEMARANG", area_type: "CITY"},
  {code: "33.23", name: "KAB. TEMANGGUNG", area_type: "CITY"},
  {code: "33.24", name: "KAB. KENDAL", area_type: "CITY"},
  {code: "33.25", name: "KAB. BATANG", area_type: "CITY"},
  {code: "33.26", name: "KAB. PEKALONGAN", area_type: "CITY"},
  {code: "33.27", name: "KAB. PEMALANG", area_type: "CITY"},
  {code: "33.28", name: "KAB. TEGAL", area_type: "CITY"},
  {code: "33.29", name: "KAB. BREBES", area_type: "CITY"},
  {code: "33.71", name: "KOTA MAGELANG", area_type: "CITY"},
  {code: "33.72", name: "KOTA SURAKARTA", area_type: "CITY"},
  {code: "33.73", name: "KOTA SALATIGA", area_type: "CITY"},
  {code: "33.74", name: "KOTA SEMARANG", area_type: "CITY"},
  {code: "33.75", name: "KOTA PEKALONGAN", area_type: "CITY"},
  {code: "33.76", name: "KOTA TEGAL", area_type: "CITY"},
  {code: "34", name: "DAERAH ISTIMEWA YOGYAKARTA", area_type: "PROVINCE"},
  {code: "34.01", name: "KAB. KULON PROGO", area_type: "CITY"},
  {code: "34.02", name: "KAB. BANTUL", area_type: "CITY"},
  {code: "34.03", name: "KAB. GUNUNGKIDUL", area_type: "CITY"},
  {code: "34.04", name: "KAB. SLEMAN", area_type: "CITY"},
  {code: "34.71", name: "KOTA YOGYAKARTA", area_type: "CITY"},
  {code: "35", name: "JAWA TIMUR", area_type: "PROVINCE"},
  {code: "35.01", name: "KAB. PACITAN", area_type: "CITY"},
  {code: "35.02", name: "KAB. PONOROGO", area_type: "CITY"},
  {code: "35.03", name: "KAB. TRENGGALEK", area_type: "CITY"},
  {code: "35.04", name: "KAB. TULUNGAGUNG", area_type: "CITY"},
  {code: "35.05", name: "KAB. BLITAR", area_type: "CITY"},
  {code: "35.06", name: "KAB. KEDIRI", area_type: "CITY"},
  {code: "35.07", name: "KAB. MALANG", area_type: "CITY"},
  {code: "35.08", name: "KAB. LUMAJANG", area_type: "CITY"},
  {code: "35.09", name: "KAB. JEMBER", area_type: "CITY"},
  {code: "35.10", name: "KAB. BANYUWANGI", area_type: "CITY"},
  {code: "35.11", name: "KAB. BONDOWOSO", area_type: "CITY"},
  {code: "35.12", name: "KAB. SITUBONDO", area_type: "CITY"},
  {code: "35.13", name: "KAB. PROBOLINGGO", area_type: "CITY"},
  {code: "35.14", name: "KAB. PASURUAN", area_type: "CITY"},
  {code: "35.15", name: "KAB. SIDOARJO", area_type: "CITY"},
  {code: "35.16", name: "KAB. MOJOKERTO", area_type: "CITY"},
  {code: "35.17", name: "KAB. JOMBANG", area_type: "CITY"},
  {code: "35.18", name: "KAB. NGANJUK", area_type: "CITY"},
  {code: "35.19", name: "KAB. MADIUN", area_type: "CITY"},
  {code: "35.20", name: "KAB. MAGETAN", area_type: "CITY"},
  {code: "35.21", name: "KAB. NGAWI", area_type: "CITY"},
  {code: "35.22", name: "KAB. BOJONEGORO", area_type: "CITY"},
  {code: "35.23", name: "KAB. TUBAN", area_type: "CITY"},
  {code: "35.24", name: "KAB. LAMONGAN", area_type: "CITY"},
  {code: "35.25", name: "KAB. GRESIK", area_type: "CITY"},
  {code: "35.26", name: "KAB. BANGKALAN", area_type: "CITY"},
  {code: "35.27", name: "KAB. SAMPANG", area_type: "CITY"},
  {code: "35.28", name: "KAB. PAMEKASAN", area_type: "CITY"},
  {code: "35.29", name: "KAB. SUMENEP", area_type: "CITY"},
  {code: "35.71", name: "KOTA KEDIRI", area_type: "CITY"},
  {code: "35.72", name: "KOTA BLITAR", area_type: "CITY"},
  {code: "35.73", name: "KOTA MALANG", area_type: "CITY"},
  {code: "35.74", name: "KOTA PROBOLINGGO", area_type: "CITY"},
  {code: "35.75", name: "KOTA PASURUAN", area_type: "CITY"},
  {code: "35.76", name: "KOTA MOJOKERTO", area_type: "CITY"},
  {code: "35.77", name: "KOTA MADIUN", area_type: "CITY"},
  {code: "35.78", name: "KOTA SURABAYA", area_type: "CITY"},
  {code: "35.79", name: "KOTA BATU", area_type: "CITY"},
  {code: "36", name: "BANTEN", area_type: "PROVINCE"},
  {code: "36.01", name: "KAB. PANDEGLANG", area_type: "CITY"},
  {code: "36.02", name: "KAB. LEBAK", area_type: "CITY"},
  {code: "36.03", name: "KAB. TANGERANG", area_type: "CITY"},
  {code: "36.04", name: "KAB. SERANG", area_type: "CITY"},
  {code: "36.71", name: "KOTA TANGERANG", area_type: "CITY"},
  {code: "36.72", name: "KOTA CILEGON", area_type: "CITY"},
  {code: "36.73", name: "KOTA SERANG", area_type: "CITY"},
  {code: "36.74", name: "KOTA TANGERANG SELATAN", area_type: "CITY"},
  {code: "51", name: "BALI", area_type: "PROVINCE"},
  {code: "51.01", name: "KAB. JEMBRANA", area_type: "CITY"},
  {code: "51.02", name: "KAB. TABANAN", area_type: "CITY"},
  {code: "51.03", name: "KAB. BADUNG", area_type: "CITY"},
  {code: "51.04", name: "KAB. GIANYAR", area_type: "CITY"},
  {code: "51.05", name: "KAB. KLUNGKUNG", area_type: "CITY"},
  {code: "51.06", name: "KAB. BANGLI", area_type: "CITY"},
  {code: "51.07", name: "KAB. KARANGASEM", area_type: "CITY"},
  {code: "51.08", name: "KAB. BULELENG", area_type: "CITY"},
  {code: "51.71", name: "KOTA DENPASAR", area_type: "CITY"}
]
