INDONESIAN_AREAS = [
  {code: "11", name: "ACEH", area_type: "PROVINCE"},
  {code: "11.01", name: "KAB. ACEH SELATAN", area_type: "CITY"},
  {code: "11.02", name: "KAB. ACEH TENGGARA", area_type: "CITY"},
  {code: "11.03", name: "KAB. ACEH TIMUR", area_type: "CITY"},
  {code: "11.04", name: "KAB. ACEH TENGAH", area_type: "CITY"},
  {code: "11.05", name: "KAB. ACEH BARAT", area_type: "CITY"},
  {code: "11.06", name: "KAB. ACEH BESAR", area_type: "CITY"},
  {code: "11.07", name: "KAB. PIDIE", area_type: "CITY"},
  {code: "11.08", name: "KAB. ACEH UTARA", area_type: "CITY"},
  {code: "11.09", name: "KAB. SIMEULUE", area_type: "CITY"},
  {code: "11.10", name: "KAB. ACEH SINGKIL", area_type: "CITY"},
  {code: "11.11", name: "KAB. BIREUEN", area_type: "CITY"},
  {code: "11.12", name: "KAB. ACEH BARAT DAYA", area_type: "CITY"},
  {code: "11.13", name: "KAB. GAYO LUES", area_type: "CITY"},
  {code: "11.14", name: "KAB. ACEH JAYA", area_type: "CITY"},
  {code: "11.15", name: "KAB. NAGAN RAYA", area_type: "CITY"},
  {code: "11.16", name: "KAB. ACEH TAMIANG", area_type: "CITY"},
  {code: "11.17", name: "KAB. BENER MERIAH", area_type: "CITY"},
  {code: "11.18", name: "KAB. PIDIE JAYA", area_type: "CITY"},
  {code: "11.71", name: "KOTA BANDA ACEH", area_type: "CITY"},
  {code: "11.72", name: "KOTA SABANG", area_type: "CITY"},
  {code: "11.73", name: "KOTA LHOKSEUMAWE", area_type: "CITY"},
  {code: "11.74", name: "KOTA LANGSA", area_type: "CITY"},
  {code: "11.75", name: "KOTA SUBULUSSALAM", area_type: "CITY"},

  {code: "12", name: "SUMATERA UTARA", area_type: "PROVINCE"},
  {code: "12.01", name: "KAB. TAPANULI TENGAH", area_type: "CITY"},
  {code: "12.02", name: "KAB. TAPANULI UTARA", area_type: "CITY"},
  {code: "12.03", name: "KAB. TAPANULI SELATAN", area_type: "CITY"},
  {code: "12.04", name: "KAB. NIAS", area_type: "CITY"},
  {code: "12.05", name: "KAB. LANGKAT", area_type: "CITY"},
  {code: "12.06", name: "KAB. KARO", area_type: "CITY"},
  {code: "12.07", name: "KAB. DELI SERDANG", area_type: "CITY"},
  {code: "12.08", name: "KAB. SIMALUNGUN", area_type: "CITY"},
  {code: "12.09", name: "KAB. ASAHAN", area_type: "CITY"},
  {code: "12.10", name: "KAB. LABUHANBATU", area_type: "CITY"},
  {code: "12.11", name: "KAB. DAIRI", area_type: "CITY"},
  {code: "12.12", name: "KAB. TOBA", area_type: "CITY"},
  {code: "12.13", name: "KAB. MANDAILING NATAL", area_type: "CITY"},
  {code: "12.14", name: "KAB. NIAS SELATAN", area_type: "CITY"},
  {code: "12.15", name: "KAB. PAKPAK BHARAT", area_type: "CITY"},
  {code: "12.16", name: "KAB. HUMBANG HASUNDUTAN", area_type: "CITY"},
  {code: "12.17", name: "KAB. SAMOSIR", area_type: "CITY"},
  {code: "12.18", name: "KAB. SERDANG BEDAGAI", area_type: "CITY"},
  {code: "12.19", name: "KAB. BATU BARA", area_type: "CITY"},
  {code: "12.20", name: "KAB. PADANG LAWAS UTARA", area_type: "CITY"},
  {code: "12.21", name: "KAB. PADANG LAWAS", area_type: "CITY"},
  {code: "12.22", name: "KAB. LABUHANBATU SELATAN", area_type: "CITY"},
  {code: "12.23", name: "KAB. LABUHANBATU UTARA", area_type: "CITY"},
  {code: "12.24", name: "KAB. NIAS UTARA", area_type: "CITY"},
  {code: "12.25", name: "KAB. NIAS BARAT", area_type: "CITY"},
  {code: "12.71", name: "KOTA MEDAN", area_type: "CITY"},
  {code: "12.72", name: "KOTA PEMATANGSIANTAR", area_type: "CITY"},
  {code: "12.73", name: "KOTA SIBOLGA", area_type: "CITY"},
  {code: "12.74", name: "KOTA TANJUNG BALAI", area_type: "CITY"},
  {code: "12.75", name: "KOTA BINJAI", area_type: "CITY"},
  {code: "12.76", name: "KOTA TEBING TINGGI", area_type: "CITY"},
  {code: "12.77", name: "KOTA PADANGSIDIMPUAN", area_type: "CITY"},
  {code: "12.78", name: "KOTA GUNUNGSITOLI", area_type: "CITY"},

  {code: "13", name: "SUMATERA BARAT", area_type: "PROVINCE"},
  {code: "13.01", name: "KAB. PESISIR SELATAN", area_type: "CITY"},
  {code: "13.02", name: "KAB. SOLOK", area_type: "CITY"},
  {code: "13.03", name: "KAB. SIJUNJUNG", area_type: "CITY"},
  {code: "13.04", name: "KAB. TANAH DATAR", area_type: "CITY"},
  {code: "13.05", name: "KAB. PADANG PARIAMAN", area_type: "CITY"},
  {code: "13.06", name: "KAB. AGAM", area_type: "CITY"},
  {code: "13.07", name: "KAB. LIMA PULUH KOTA", area_type: "CITY"},
  {code: "13.08", name: "KAB. PASAMAN", area_type: "CITY"},
  {code: "13.09", name: "KAB. KEPULAUAN MENTAWAI", area_type: "CITY"},
  {code: "13.10", name: "KAB. DHARMASRAYA", area_type: "CITY"},
  {code: "13.11", name: "KAB. SOLOK SELATAN", area_type: "CITY"},
  {code: "13.12", name: "KAB. PASAMAN BARAT", area_type: "CITY"},
  {code: "13.71", name: "KOTA PADANG", area_type: "CITY"},
  {code: "13.72", name: "KOTA SOLOK", area_type: "CITY"},
  {code: "13.73", name: "KOTA SAWAHLUNTO", area_type: "CITY"},
  {code: "13.74", name: "KOTA PADANG PANJANG", area_type: "CITY"},
  {code: "13.75", name: "KOTA BUKITTINGGI", area_type: "CITY"},
  {code: "13.76", name: "KOTA PAYAKUMBUH", area_type: "CITY"},
  {code: "13.77", name: "KOTA PARIAMAN", area_type: "CITY"},

  {code: "14", name: "RIAU", area_type: "PROVINCE"},
  {code: "14.01", name: "KAB. KAMPAR", area_type: "CITY"},
  {code: "14.02", name: "KAB. INDRAGIRI HULU", area_type: "CITY"},
  {code: "14.03", name: "KAB. BENGKALIS", area_type: "CITY"},
  {code: "14.04", name: "KAB. INDRAGIRI HILIR", area_type: "CITY"},
  {code: "14.05", name: "KAB. PELALAWAN", area_type: "CITY"},
  {code: "14.06", name: "KAB. ROKAN HULU", area_type: "CITY"},
  {code: "14.07", name: "KAB. ROKAN HILIR", area_type: "CITY"},
  {code: "14.08", name: "KAB. SIAK", area_type: "CITY"},
  {code: "14.09", name: "KAB. KUANTAN SINGINGI", area_type: "CITY"},
  {code: "14.10", name: "KAB. KEPULAUAN MERANTI", area_type: "CITY"},
  {code: "14.71", name: "KOTA PEKANBARU", area_type: "CITY"},
  {code: "14.72", name: "KOTA DUMAI", area_type: "CITY"},

  {code: "15", name: "JAMBI", area_type: "PROVINCE"},
  {code: "15.01", name: "KAB. KERINCI", area_type: "CITY"},
  {code: "15.02", name: "KAB. MERANGIN", area_type: "CITY"},
  {code: "15.03", name: "KAB. SAROLANGUN", area_type: "CITY"},
  {code: "15.04", name: "KAB. BATANGHARI", area_type: "CITY"},
  {code: "15.05", name: "KAB. MUARO JAMBI", area_type: "CITY"},
  {code: "15.06", name: "KAB. TANJUNG JABUNG BARAT", area_type: "CITY"},
  {code: "15.07", name: "KAB. TANJUNG JABUNG TIMUR", area_type: "CITY"},
  {code: "15.08", name: "KAB. BUNGO", area_type: "CITY"},
  {code: "15.09", name: "KAB. TEBO", area_type: "CITY"},
  {code: "15.71", name: "KOTA JAMBI", area_type: "CITY"},
  {code: "15.72", name: "KOTA SUNGAI PENUH", area_type: "CITY"},

  {code: "16", name: "SUMATERA SELATAN", area_type: "PROVINCE"},
  {code: "16.01", name: "KAB. OGAN KOMERING ULU", area_type: "CITY"},
  {code: "16.02", name: "KAB. OGAN KOMERING ILIR", area_type: "CITY"},
  {code: "16.03", name: "KAB. MUARA ENIM", area_type: "CITY"},
  {code: "16.04", name: "KAB. LAHAT", area_type: "CITY"},
  {code: "16.05", name: "KAB. MUSI RAWAS", area_type: "CITY"},
  {code: "16.06", name: "KAB. MUSI BANYUASIN", area_type: "CITY"},
  {code: "16.07", name: "KAB. BANYUASIN", area_type: "CITY"},
  {code: "16.08", name: "KAB. OGAN KOMERING ULU TIMUR", area_type: "CITY"},
  {code: "16.09", name: "KAB. OGAN KOMERING ULU SELATAN", area_type: "CITY"},
  {code: "16.10", name: "KAB. OGAN ILIR", area_type: "CITY"},
  {code: "16.11", name: "KAB. EMPAT LAWANG", area_type: "CITY"},
  {code: "16.12", name: "KAB. PENUKAL ABAB LEMATANG ILIR", area_type: "CITY"},
  {code: "16.13", name: "KAB. MUSI RAWAS UTARA", area_type: "CITY"},
  {code: "16.71", name: "KOTA PALEMBANG", area_type: "CITY"},
  {code: "16.72", name: "KOTA PAGAR ALAM", area_type: "CITY"},
  {code: "16.73", name: "KOTA LUBUK LINGGAU", area_type: "CITY"},
  {code: "16.74", name: "KOTA PRABUMULIH", area_type: "CITY"},

  {code: "17", name: "BENGKULU", area_type: "PROVINCE"},
  {code: "17.01", name: "KAB. BENGKULU SELATAN", area_type: "CITY"},
  {code: "17.02", name: "KAB. REJANG LEBONG", area_type: "CITY"},
  {code: "17.03", name: "KAB. BENGKULU UTARA", area_type: "CITY"},
  {code: "17.04", name: "KAB. KAUR", area_type: "CITY"},
  {code: "17.05", name: "KAB. SELUMA", area_type: "CITY"},
  {code: "17.06", name: "KAB. MUKO MUKO", area_type: "CITY"},
  {code: "17.07", name: "KAB. LEBONG", area_type: "CITY"},
  {code: "17.08", name: "KAB. KEPAHIANG", area_type: "CITY"},
  {code: "17.09", name: "KAB. BENGKULU TENGAH", area_type: "CITY"},
  {code: "17.71", name: "KOTA BENGKULU", area_type: "CITY"},

  {code: "18", name: "LAMPUNG", area_type: "PROVINCE"},
  {code: "18.01", name: "KAB. LAMPUNG SELATAN", area_type: "CITY"},
  {code: "18.02", name: "KAB. LAMPUNG TENGAH", area_type: "CITY"},
  {code: "18.03", name: "KAB. LAMPUNG UTARA", area_type: "CITY"},
  {code: "18.04", name: "KAB. LAMPUNG BARAT", area_type: "CITY"},
  {code: "18.05", name: "KAB. TULANG BAWANG", area_type: "CITY"},
  {code: "18.06", name: "KAB. TANGGAMUS", area_type: "CITY"},
  {code: "18.07", name: "KAB. LAMPUNG TIMUR", area_type: "CITY"},
  {code: "18.08", name: "KAB. WAY KANAN", area_type: "CITY"},
  {code: "18.09", name: "KAB. PESAWARAN", area_type: "CITY"},
  {code: "18.10", name: "KAB. PRINGSEWU", area_type: "CITY"},
  {code: "18.11", name: "KAB. MESUJI", area_type: "CITY"},
  {code: "18.12", name: "KAB. TULANG BAWANG BARAT", area_type: "CITY"},
  {code: "18.13", name: "KAB. PESISIR BARAT", area_type: "CITY"},
  {code: "18.71", name: "KOTA BANDAR LAMPUNG", area_type: "CITY"},
  {code: "18.72", name: "KOTA METRO", area_type: "CITY"},

  {code: "19", name: "KEPULAUAN BANGKA BELITUNG", area_type: "PROVINCE"},
  {code: "19.01", name: "KAB. BANGKA", area_type: "CITY"},
  {code: "19.02", name: "KAB. BELITUNG", area_type: "CITY"},
  {code: "19.03", name: "KAB. BANGKA SELATAN", area_type: "CITY"},
  {code: "19.04", name: "KAB. BANGKA TENGAH", area_type: "CITY"},
  {code: "19.05", name: "KAB. BANGKA BARAT", area_type: "CITY"},
  {code: "19.06", name: "KAB. BELITUNG TIMUR", area_type: "CITY"},
  {code: "19.71", name: "KOTA PANGKAL PINANG", area_type: "CITY"},

  {code: "21", name: "KEPULAUAN RIAU", area_type: "PROVINCE"},
  {code: "21.01", name: "KAB. BINTAN", area_type: "CITY"},
  {code: "21.02", name: "KAB. KARIMUN", area_type: "CITY"},
  {code: "21.03", name: "KAB. NATUNA", area_type: "CITY"},
  {code: "21.04", name: "KAB. LINGGA", area_type: "CITY"},
  {code: "21.05", name: "KAB. KEPULAUAN ANAMBAS", area_type: "CITY"},
  {code: "21.71", name: "KOTA BATAM", area_type: "CITY"},
  {code: "21.72", name: "KOTA TANJUNG PINANG", area_type: "CITY"},

  {code: "31", name: "DKI JAKARTA", area_type: "PROVINCE"},
  {code: "31.01", name: "KAB. ADM. KEP. SERIBU", area_type: "CITY"},
  {code: "31.71", name: "KOTA ADM. JAKARTA PUSAT", area_type: "CITY"},
  {code: "31.72", name: "KOTA ADM. JAKARTA UTARA", area_type: "CITY"},
  {code: "31.73", name: "KOTA ADM. JAKARTA BARAT", area_type: "CITY"},
  {code: "31.74", name: "KOTA ADM. JAKARTA SELATAN", area_type: "CITY"},
  {code: "31.75", name: "KOTA ADM. JAKARTA TIMUR", area_type: "CITY"},

  {code: "32", name: "JAWA BARAT", area_type: "PROVINCE"},
  {code: "32.01", name: "KAB. BOGOR", area_type: "CITY"},
  {code: "32.02", name: "KAB. SUKABUMI", area_type: "CITY"},
  {code: "32.03", name: "KAB. CIANJUR", area_type: "CITY"},
  {code: "32.04", name: "KAB. BANDUNG", area_type: "CITY"},
  {code: "32.05", name: "KAB. GARUT", area_type: "CITY"},
  {code: "32.06", name: "KAB. TASIKMALAYA", area_type: "CITY"},
  {code: "32.07", name: "KAB. CIAMIS", area_type: "CITY"},
  {code: "32.08", name: "KAB. KUNINGAN", area_type: "CITY"},
  {code: "32.09", name: "KAB. CIREBON", area_type: "CITY"},
  {code: "32.10", name: "KAB. MAJALENGKA", area_type: "CITY"},
  {code: "32.11", name: "KAB. SUMEDANG", area_type: "CITY"},
  {code: "32.12", name: "KAB. INDRAMAYU", area_type: "CITY"},
  {code: "32.13", name: "KAB. SUBANG", area_type: "CITY"},
  {code: "32.14", name: "KAB. PURWAKARTA", area_type: "CITY"},
  {code: "32.15", name: "KAB. KARAWANG", area_type: "CITY"},
  {code: "32.16", name: "KAB. BEKASI", area_type: "CITY"},
  {code: "32.17", name: "KAB. BANDUNG BARAT", area_type: "CITY"},
  {code: "32.18", name: "KAB. PANGANDARAN", area_type: "CITY"},
  {code: "32.71", name: "KOTA BOGOR", area_type: "CITY"},
  {code: "32.72", name: "KOTA SUKABUMI", area_type: "CITY"},
  {code: "32.73", name: "KOTA BANDUNG", area_type: "CITY"},
  {code: "32.74", name: "KOTA CIREBON", area_type: "CITY"},
  {code: "32.75", name: "KOTA BEKASI", area_type: "CITY"},
  {code: "32.76", name: "KOTA DEPOK", area_type: "CITY"},
  {code: "32.77", name: "KOTA CIMAHI", area_type: "CITY"},
  {code: "32.78", name: "KOTA TASIKMALAYA", area_type: "CITY"},
  {code: "32.79", name: "KOTA BANJAR", area_type: "CITY"},

  {code: "33", name: "JAWA TENGAH", area_type: "PROVINCE"},
  {code: "33.01", name: "KAB. CILACAP", area_type: "CITY"},
  {code: "33.02", name: "KAB. BANYUMAS", area_type: "CITY"},
  {code: "33.03", name: "KAB. PURBALINGGA", area_type: "CITY"},
  {code: "33.04", name: "KAB. BANJARNEGARA", area_type: "CITY"},
  {code: "33.05", name: "KAB. KEBUMEN", area_type: "CITY"},
  {code: "33.06", name: "KAB. PURWOREJO", area_type: "CITY"},
  {code: "33.07", name: "KAB. WONOSOBO", area_type: "CITY"},
  {code: "33.08", name: "KAB. MAGELANG", area_type: "CITY"},
  {code: "33.09", name: "KAB. BOYOLALI", area_type: "CITY"},
  {code: "33.10", name: "KAB. KLATEN", area_type: "CITY"},
  {code: "33.11", name: "KAB. SUKOHARJO", area_type: "CITY"},
  {code: "33.12", name: "KAB. WONOGIRI", area_type: "CITY"},
  {code: "33.13", name: "KAB. KARANGANYAR", area_type: "CITY"},
  {code: "33.14", name: "KAB. SRAGEN", area_type: "CITY"},
  {code: "33.15", name: "KAB. GROBOGAN", area_type: "CITY"},
  {code: "33.16", name: "KAB. BLORA", area_type: "CITY"},
  {code: "33.17", name: "KAB. REMBANG", area_type: "CITY"},
  {code: "33.18", name: "KAB. PATI", area_type: "CITY"},
  {code: "33.19", name: "KAB. KUDUS", area_type: "CITY"},
  {code: "33.20", name: "KAB. JEPARA", area_type: "CITY"},
  {code: "33.21", name: "KAB. DEMAK", area_type: "CITY"},
  {code: "33.22", name: "KAB. SEMARANG", area_type: "CITY"},
  {code: "33.23", name: "KAB. TEMANGGUNG", area_type: "CITY"},
  {code: "33.24", name: "KAB. KENDAL", area_type: "CITY"},
  {code: "33.25", name: "KAB. BATANG", area_type: "CITY"},
  {code: "33.26", name: "KAB. PEKALONGAN", area_type: "CITY"},
  {code: "33.27", name: "KAB. PEMALANG", area_type: "CITY"},
  {code: "33.28", name: "KAB. TEGAL", area_type: "CITY"},
  {code: "33.29", name: "KAB. BREBES", area_type: "CITY"},
  {code: "33.71", name: "KOTA MAGELANG", area_type: "CITY"},
  {code: "33.72", name: "KOTA SURAKARTA", area_type: "CITY"},
  {code: "33.73", name: "KOTA SALATIGA", area_type: "CITY"},
  {code: "33.74", name: "KOTA SEMARANG", area_type: "CITY"},
  {code: "33.75", name: "KOTA PEKALONGAN", area_type: "CITY"},
  {code: "33.76", name: "KOTA TEGAL", area_type: "CITY"},

  {code: "34", name: "DAERAH ISTIMEWA YOGYAKARTA", area_type: "PROVINCE"},
  {code: "34.01", name: "KAB. KULON PROGO", area_type: "CITY"},
  {code: "34.02", name: "KAB. BANTUL", area_type: "CITY"},
  {code: "34.03", name: "KAB. GUNUNGKIDUL", area_type: "CITY"},
  {code: "34.04", name: "KAB. SLEMAN", area_type: "CITY"},
  {code: "34.71", name: "KOTA YOGYAKARTA", area_type: "CITY"},

  {code: "35", name: "JAWA TIMUR", area_type: "PROVINCE"},
  {code: "35.01", name: "KAB. PACITAN", area_type: "CITY"},
  {code: "35.02", name: "KAB. PONOROGO", area_type: "CITY"},
  {code: "35.03", name: "KAB. TRENGGALEK", area_type: "CITY"},
  {code: "35.04", name: "KAB. TULUNGAGUNG", area_type: "CITY"},
  {code: "35.05", name: "KAB. BLITAR", area_type: "CITY"},
  {code: "35.06", name: "KAB. KEDIRI", area_type: "CITY"},
  {code: "35.07", name: "KAB. MALANG", area_type: "CITY"},
  {code: "35.08", name: "KAB. LUMAJANG", area_type: "CITY"},
  {code: "35.09", name: "KAB. JEMBER", area_type: "CITY"},
  {code: "35.10", name: "KAB. BANYUWANGI", area_type: "CITY"},
  {code: "35.11", name: "KAB. BONDOWOSO", area_type: "CITY"},
  {code: "35.12", name: "KAB. SITUBONDO", area_type: "CITY"},
  {code: "35.13", name: "KAB. PROBOLINGGO", area_type: "CITY"},
  {code: "35.14", name: "KAB. PASURUAN", area_type: "CITY"},
  {code: "35.15", name: "KAB. SIDOARJO", area_type: "CITY"},
  {code: "35.16", name: "KAB. MOJOKERTO", area_type: "CITY"},
  {code: "35.17", name: "KAB. JOMBANG", area_type: "CITY"},
  {code: "35.18", name: "KAB. NGANJUK", area_type: "CITY"},
  {code: "35.19", name: "KAB. MADIUN", area_type: "CITY"},
  {code: "35.20", name: "KAB. MAGETAN", area_type: "CITY"},
  {code: "35.21", name: "KAB. NGAWI", area_type: "CITY"},
  {code: "35.22", name: "KAB. BOJONEGORO", area_type: "CITY"},
  {code: "35.23", name: "KAB. TUBAN", area_type: "CITY"},
  {code: "35.24", name: "KAB. LAMONGAN", area_type: "CITY"},
  {code: "35.25", name: "KAB. GRESIK", area_type: "CITY"},
  {code: "35.26", name: "KAB. BANGKALAN", area_type: "CITY"},
  {code: "35.27", name: "KAB. SAMPANG", area_type: "CITY"},
  {code: "35.28", name: "KAB. PAMEKASAN", area_type: "CITY"},
  {code: "35.29", name: "KAB. SUMENEP", area_type: "CITY"},
  {code: "35.71", name: "KOTA KEDIRI", area_type: "CITY"},
  {code: "35.72", name: "KOTA BLITAR", area_type: "CITY"},
  {code: "35.73", name: "KOTA MALANG", area_type: "CITY"},
  {code: "35.74", name: "KOTA PROBOLINGGO", area_type: "CITY"},
  {code: "35.75", name: "KOTA PASURUAN", area_type: "CITY"},
  {code: "35.76", name: "KOTA MOJOKERTO", area_type: "CITY"},
  {code: "35.77", name: "KOTA MADIUN", area_type: "CITY"},
  {code: "35.78", name: "KOTA SURABAYA", area_type: "CITY"},
  {code: "35.79", name: "KOTA BATU", area_type: "CITY"},

  {code: "36", name: "BANTEN", area_type: "PROVINCE"},
  {code: "36.01", name: "KAB. PANDEGLANG", area_type: "CITY"},
  {code: "36.02", name: "KAB. LEBAK", area_type: "CITY"},
  {code: "36.03", name: "KAB. TANGERANG", area_type: "CITY"},
  {code: "36.04", name: "KAB. SERANG", area_type: "CITY"},
  {code: "36.71", name: "KOTA TANGERANG", area_type: "CITY"},
  {code: "36.72", name: "KOTA CILEGON", area_type: "CITY"},
  {code: "36.73", name: "KOTA SERANG", area_type: "CITY"},
  {code: "36.74", name: "KOTA TANGERANG SELATAN", area_type: "CITY"},

  {code: "51", name: "BALI", area_type: "PROVINCE"},
  {code: "51.01", name: "KAB. JEMBRANA", area_type: "CITY"},
  {code: "51.02", name: "KAB. TABANAN", area_type: "CITY"},
  {code: "51.03", name: "KAB. BADUNG", area_type: "CITY"},
  {code: "51.04", name: "KAB. GIANYAR", area_type: "CITY"},
  {code: "51.05", name: "KAB. KLUNGKUNG", area_type: "CITY"},
  {code: "51.06", name: "KAB. BANGLI", area_type: "CITY"},
  {code: "51.07", name: "KAB. KARANGASEM", area_type: "CITY"},
  {code: "51.08", name: "KAB. BULELENG", area_type: "CITY"},
  {code: "51.71", name: "KOTA DENPASAR", area_type: "CITY"},

  {code: "52", name: "NUSA TENGGARA BARAT", area_type: "PROVINCE"},
  {code: "52.01", name: "KAB. LOMBOK BARAT", area_type: "CITY"},
  {code: "52.02", name: "KAB. LOMBOK TENGAH", area_type: "CITY"},
  {code: "52.03", name: "KAB. LOMBOK TIMUR", area_type: "CITY"},
  {code: "52.04", name: "KAB. SUMBAWA", area_type: "CITY"},
  {code: "52.05", name: "KAB. DOMPU", area_type: "CITY"},
  {code: "52.06", name: "KAB. BIMA", area_type: "CITY"},
  {code: "52.07", name: "KAB. SUMBAWA BARAT", area_type: "CITY"},
  {code: "52.08", name: "KAB. LOMBOK UTARA", area_type: "CITY"},
  {code: "52.71", name: "KOTA MATARAM", area_type: "CITY"},
  {code: "52.72", name: "KOTA BIMA", area_type: "CITY"},

  {code: "53", name: "NUSA TENGGARA TIMUR", area_type: "PROVINCE"},
  {code: "53.01", name: "KAB. KUPANG", area_type: "CITY"},
  {code: "53.02", name: "KAB. TIMOR TENGAH SELATAN", area_type: "CITY"},
  {code: "53.03", name: "KAB. TIMOR TENGAH UTARA", area_type: "CITY"},
  {code: "53.04", name: "KAB. BELU", area_type: "CITY"},
  {code: "53.05", name: "KAB. ALOR", area_type: "CITY"},
  {code: "53.06", name: "KAB. FLORES TIMUR", area_type: "CITY"},
  {code: "53.07", name: "KAB. SIKKA", area_type: "CITY"},
  {code: "53.08", name: "KAB. ENDE", area_type: "CITY"},
  {code: "53.09", name: "KAB. NGADA", area_type: "CITY"},
  {code: "53.10", name: "KAB. MANGGARAI", area_type: "CITY"},
  {code: "53.11", name: "KAB. SUMBA TIMUR", area_type: "CITY"},
  {code: "53.12", name: "KAB. SUMBA BARAT", area_type: "CITY"},
  {code: "53.13", name: "KAB. LEMBATA", area_type: "CITY"},
  {code: "53.14", name: "KAB. ROTE NDAO", area_type: "CITY"},
  {code: "53.15", name: "KAB. MANGGARAI BARAT", area_type: "CITY"},
  {code: "53.16", name: "KAB. NAGEKEO", area_type: "CITY"},
  {code: "53.17", name: "KAB. SUMBA TENGAH", area_type: "CITY"},
  {code: "53.18", name: "KAB. SUMBA BARAT DAYA", area_type: "CITY"},
  {code: "53.19", name: "KAB. MANGGARAI TIMUR", area_type: "CITY"},
  {code: "53.20", name: "KAB. SABU RAIJUA", area_type: "CITY"},
  {code: "53.21", name: "KAB. MALAKA", area_type: "CITY"},
  {code: "53.71", name: "KOTA KUPANG", area_type: "CITY"},

  {code: "61", name: "KALIMANTAN BARAT", area_type: "PROVINCE"},
  {code: "61.01", name: "KAB. SAMBAS", area_type: "CITY"},
  {code: "61.02", name: "KAB. MEMPAWAH", area_type: "CITY"},
  {code: "61.03", name: "KAB. SANGGAU", area_type: "CITY"},
  {code: "61.04", name: "KAB. KETAPANG", area_type: "CITY"},
  {code: "61.05", name: "KAB. SINTANG", area_type: "CITY"},
  {code: "61.06", name: "KAB. KAPUAS HULU", area_type: "CITY"},
  {code: "61.07", name: "KAB. BENGKAYANG", area_type: "CITY"},
  {code: "61.08", name: "KAB. LANDAK", area_type: "CITY"},
  {code: "61.09", name: "KAB. SEKADAU", area_type: "CITY"},
  {code: "61.10", name: "KAB. MELAWI", area_type: "CITY"},
  {code: "61.11", name: "KAB. KAYONG UTARA", area_type: "CITY"},
  {code: "61.12", name: "KAB. KUBU RAYA", area_type: "CITY"},
  {code: "61.71", name: "KOTA PONTIANAK", area_type: "CITY"},
  {code: "61.72", name: "KOTA SINGKAWANG", area_type: "CITY"},

  {code: "62", name: "KALIMANTAN TENGAH", area_type: "PROVINCE"},
  {code: "62.01", name: "KAB. KOTAWARINGIN BARAT", area_type: "CITY"},
  {code: "62.02", name: "KAB. KOTAWARINGIN TIMUR", area_type: "CITY"},
  {code: "62.03", name: "KAB. KAPUAS", area_type: "CITY"},
  {code: "62.04", name: "KAB. BARITO SELATAN", area_type: "CITY"},
  {code: "62.05", name: "KAB. BARITO UTARA", area_type: "CITY"},
  {code: "62.06", name: "KAB. KATINGAN", area_type: "CITY"},
  {code: "62.07", name: "KAB. SERUYAN", area_type: "CITY"},
  {code: "62.08", name: "KAB. SUKAMARA", area_type: "CITY"},
  {code: "62.09", name: "KAB. LAMANDAU", area_type: "CITY"},
  {code: "62.10", name: "KAB. GUNUNG MAS", area_type: "CITY"},
  {code: "62.11", name: "KAB. PULANG PISAU", area_type: "CITY"},
  {code: "62.12", name: "KAB. MURUNG RAYA", area_type: "CITY"},
  {code: "62.13", name: "KAB. BARITO TIMUR", area_type: "CITY"},
  {code: "62.71", name: "KOTA PALANGKARAYA", area_type: "CITY"},

  {code: "63", name: "KALIMANTAN SELATAN", area_type: "PROVINCE"},
  {code: "63.01", name: "KAB. TANAH LAUT", area_type: "CITY"},
  {code: "63.02", name: "KAB. KOTABARU", area_type: "CITY"},
  {code: "63.03", name: "KAB. BANJAR", area_type: "CITY"},
  {code: "63.04", name: "KAB. BARITO KUALA", area_type: "CITY"},
  {code: "63.05", name: "KAB. TAPIN", area_type: "CITY"},
  {code: "63.06", name: "KAB. HULU SUNGAI SELATAN", area_type: "CITY"},
  {code: "63.07", name: "KAB. HULU SUNGAI TENGAH", area_type: "CITY"},
  {code: "63.08", name: "KAB. HULU SUNGAI UTARA", area_type: "CITY"},
  {code: "63.09", name: "KAB. TABALONG", area_type: "CITY"},
  {code: "63.10", name: "KAB. TANAH BUMBU", area_type: "CITY"},
  {code: "63.11", name: "KAB. BALANGAN", area_type: "CITY"},
  {code: "63.71", name: "KOTA BANJARMASIN", area_type: "CITY"},
  {code: "63.72", name: "KOTA BANJARBARU", area_type: "CITY"},

  {code: "64", name: "KALIMANTAN TIMUR", area_type: "PROVINCE"},
  {code: "64.01", name: "KAB. PASER", area_type: "PROVINCE"},
  {code: "64.02", name: "KAB. KUTAI KARTANEGARA", area_type: "PROVINCE"},
  {code: "64.03", name: "KAB. BERAU", area_type: "PROVINCE"},
  {code: "64.07", name: "KAB. KUTAI BARAT", area_type: "PROVINCE"},
  {code: "64.08", name: "KAB. KUTAI TIMUR", area_type: "PROVINCE"},
  {code: "64.09", name: "KAB. PENAJAM PASER UTARA", area_type: "PROVINCE"},
  {code: "64.11", name: "KAB. MAHAKAM ULU", area_type: "PROVINCE"},
  {code: "64.71", name: "KOTA BALIKPAPAN", area_type: "PROVINCE"},
  {code: "64.72", name: "KOTA SAMARINDA", area_type: "PROVINCE"},
  {code: "64.74", name: "KOTA BONTANG", area_type: "PROVINCE"},

  {code: "65", name: "KALIMANTAN UTARA", area_type: "PROVINCE"},
  {code: "65.01", name: "KAB. BULUNGAN", area_type: "CITY"},
  {code: "65.02", name: "KAB. MALINAU", area_type: "CITY"},
  {code: "65.03", name: "KAB. NUNUKAN", area_type: "CITY"},
  {code: "65.04", name: "KAB. TANA TIDUNG", area_type: "CITY"},
  {code: "65.71", name: "KOTA TARAKAN", area_type: "CITY"},

  {code: "71", name: "SULAWESI UTARA", area_type: "PROVINCE"},
  {code: "71.01", name: "KAB. BOLAANG MONGONDOW", area_type: "CITY"},
  {code: "71.02", name: "KAB. MINAHASA", area_type: "CITY"},
  {code: "71.03", name: "KAB. KEPULAUAN SANGIHE", area_type: "CITY"},
  {code: "71.04", name: "KAB. KEPULAUAN TALAUD", area_type: "CITY"},
  {code: "71.05", name: "KAB. MINAHASA SELATAN", area_type: "CITY"},
  {code: "71.06", name: "KAB. MINAHASA UTARA", area_type: "CITY"},
  {code: "71.07", name: "KAB. MINAHASA TENGGARA", area_type: "CITY"},
  {code: "71.08", name: "KAB. BOLAANG MONGONDOW UTARA", area_type: "CITY"},
  {code: "71.09", name: "KAB. KEP. SIAU TAGULANDANG BIARO", area_type: "CITY"},
  {code: "71.10", name: "KAB. BOLAANG MONGONDOW TIMUR", area_type: "CITY"},
  {code: "71.11", name: "KAB. BOLAANG MONGONDOW SELATAN", area_type: "CITY"},
  {code: "71.71", name: "KOTA MANADO", area_type: "CITY"},
  {code: "71.72", name: "KOTA BITUNG", area_type: "CITY"},
  {code: "71.73", name: "KOTA TOMOHON", area_type: "CITY"},
  {code: "71.74", name: "KOTA KOTAMOBAGU", area_type: "CITY"},

  {code: "72", name: "SULAWESI TENGAH", area_type: "PROVINCE"},
  {code: "72.01", name: "KAB. BANGGAI", area_type: "CITY"},
  {code: "72.02", name: "KAB. POSO", area_type: "CITY"},
  {code: "72.03", name: "KAB. DONGGALA", area_type: "CITY"},
  {code: "72.04", name: "KAB. TOLI TOLI", area_type: "CITY"},
  {code: "72.05", name: "KAB. BUOL", area_type: "CITY"},
  {code: "72.06", name: "KAB. MOROWALI", area_type: "CITY"},
  {code: "72.07", name: "KAB. BANGGAI KEPULAUAN", area_type: "CITY"},
  {code: "72.08", name: "KAB. PARIGI MOUTONG", area_type: "CITY"},
  {code: "72.09", name: "KAB. TOJO UNA UNA", area_type: "CITY"},
  {code: "72.10", name: "KAB. SIGI", area_type: "CITY"},
  {code: "72.11", name: "KAB. BANGGAI LAUT", area_type: "CITY"},
  {code: "72.12", name: "KAB. MOROWALI UTARA", area_type: "CITY"},
  {code: "72.71", name: "KOTA PALU", area_type: "CITY"},

  {code: "73", name: "SULAWESI SELATAN", area_type: "PROVINCE"},
  {code: "73.01", name: "KAB. KEPULAUAN SELAYAR", area_type: "CITY"},
  {code: "73.02", name: "KAB. BULUKUMBA", area_type: "CITY"},
  {code: "73.03", name: "KAB. BANTAENG", area_type: "CITY"},
  {code: "73.04", name: "KAB. JENEPONTO", area_type: "CITY"},
  {code: "73.05", name: "KAB. TAKALAR", area_type: "CITY"},
  {code: "73.06", name: "KAB. GOWA", area_type: "CITY"},
  {code: "73.07", name: "KAB. SINJAI", area_type: "CITY"},
  {code: "73.08", name: "KAB. BONE", area_type: "CITY"},
  {code: "73.09", name: "KAB. MAROS", area_type: "CITY"},
  {code: "73.10", name: "KAB. PANGKAJENE KEPULAUAN", area_type: "CITY"},
  {code: "73.11", name: "KAB. BARRU", area_type: "CITY"},
  {code: "73.12", name: "KAB. SOPPENG", area_type: "CITY"},
  {code: "73.13", name: "KAB. WAJO", area_type: "CITY"},
  {code: "73.14", name: "KAB. SIDENRENG RAPPANG", area_type: "CITY"},
  {code: "73.15", name: "KAB. PINRANG", area_type: "CITY"},
  {code: "73.16", name: "KAB. ENREKANG", area_type: "CITY"},
  {code: "73.17", name: "KAB. LUWU", area_type: "CITY"},
  {code: "73.18", name: "KAB. TANA TORAJA", area_type: "CITY"},
  {code: "73.22", name: "KAB. LUWU UTARA", area_type: "CITY"},
  {code: "73.24", name: "KAB. LUWU TIMUR", area_type: "CITY"},
  {code: "73.26", name: "KAB. TORAJA UTARA", area_type: "CITY"},
  {code: "73.71", name: "KOTA MAKASSAR", area_type: "CITY"},
  {code: "73.72", name: "KOTA PARE PARE", area_type: "CITY"},
  {code: "73.73", name: "KOTA PALOPO", area_type: "CITY"},

  {code: "74", name: "SULAWESI TENGGARA", area_type: "PROVINCE"},
  {code: "74.01", name: "KAB. KOLAKA", area_type: "CITY"},
  {code: "74.02", name: "KAB. KONAWE", area_type: "CITY"},
  {code: "74.03", name: "KAB. MUNA", area_type: "CITY"},
  {code: "74.04", name: "KAB. BUTON", area_type: "CITY"},
  {code: "74.05", name: "KAB. KONAWE SELATAN", area_type: "CITY"},
  {code: "74.06", name: "KAB. BOMBANA", area_type: "CITY"},
  {code: "74.07", name: "KAB. WAKATOBI", area_type: "CITY"},
  {code: "74.08", name: "KAB. KOLAKA UTARA", area_type: "CITY"},
  {code: "74.09", name: "KAB. KONAWE UTARA", area_type: "CITY"},
  {code: "74.10", name: "KAB. BUTON UTARA", area_type: "CITY"},
  {code: "74.11", name: "KAB. KOLAKA TIMUR", area_type: "CITY"},
  {code: "74.12", name: "KAB. KONAWE KEPULAUAN", area_type: "CITY"},
  {code: "74.13", name: "KAB. MUNA BARAT", area_type: "CITY"},
  {code: "74.14", name: "KAB. BUTON TENGAH", area_type: "CITY"},
  {code: "74.15", name: "KAB. BUTON SELATAN", area_type: "CITY"},
  {code: "74.71", name: "KOTA KENDARI", area_type: "CITY"},
  {code: "74.72", name: "KOTA BAU BAU", area_type: "CITY"},

  {code: "75", name: "GORONTALO", area_type: "PROVINCE"},
  {code: "75.01", name: "KAB. GORONTALO", area_type: "CITY"},
  {code: "75.02", name: "KAB. BOALEMO", area_type: "CITY"},
  {code: "75.03", name: "KAB. BONE BOLANGO", area_type: "CITY"},
  {code: "75.04", name: "KAB. POHUWATO", area_type: "CITY"},
  {code: "75.05", name: "KAB. GORONTALO UTARA", area_type: "CITY"},
  {code: "75.71", name: "KOTA GORONTALO", area_type: "CITY"},

  {code: "76", name: "SULAWESI BARAT", area_type: "PROVINCE"},
  {code: "76.01", name: "KAB. PASANGKAYU", area_type: "CITY"},
  {code: "76.02", name: "KAB. MAMUJU", area_type: "CITY"},
  {code: "76.03", name: "KAB. MAMASA", area_type: "CITY"},
  {code: "76.04", name: "KAB. POLEWALI MANDAR", area_type: "CITY"},
  {code: "76.05", name: "KAB. MAJENE", area_type: "CITY"},
  {code: "76.06", name: "KAB. MAMUJU TENGAH", area_type: "CITY"},

  {code: "92", name: "PAPUA BARAT", area_type: "PROVINCE"},
  {code: "92.01", name: "KAB. SORONG", area_type: "CITY"},
  {code: "92.02", name: "KAB. MANOKWARI", area_type: "CITY"},
  {code: "92.03", name: "KAB. FAK FAK", area_type: "CITY"},
  {code: "92.04", name: "KAB. SORONG SELATAN", area_type: "CITY"},
  {code: "92.05", name: "KAB. RAJA AMPAT", area_type: "CITY"},
  {code: "92.06", name: "KAB. TELUK BINTUNI", area_type: "CITY"},
  {code: "92.07", name: "KAB. TELUK WONDAMA", area_type: "CITY"},
  {code: "92.08", name: "KAB. KAIMANA", area_type: "CITY"},
  {code: "92.09", name: "KAB. TAMBRAUW", area_type: "CITY"},
  {code: "92.10", name: "KAB. MAYBRAT", area_type: "CITY"},
  {code: "92.11", name: "KAB. MANOKWARI SELATAN", area_type: "CITY"},
  {code: "92.12", name: "KAB. PEGUNUNGAN ARFAK", area_type: "CITY"},
  {code: "92.71", name: "KOTA SORONG", area_type: "CITY"}
]
