LOCATIONS_DATA = [
  {country: "INDONESIA", country_code: "ID", state: "DKI JAKARTA", city: "KOTA ADM. JAKARTA SELATAN"},
  {country: "INDONESIA", country_code: "ID", state: "DKI JAKARTA", city: "KOTA ADM. JAKARTA BARAT"},
  {country: "INDONESIA", country_code: "ID", state: "DKI JAKARTA", city: "KOTA ADM. JAKARTA TIMUR"},
  {country: "INDONESIA", country_code: "ID", state: "DKI JAKARTA", city: "KOTA ADM. JAKARTA UTARA"},
  {country: "INDONESIA", country_code: "ID", state: "DKI JAKARTA", city: "KOTA ADM. JAKARTA PUSAT"},
  {country: "INDONESIA", country_code: "ID", state: "BANTEN", city: "KOTA TANGERANG SELATAN"},
  {country: "INDONESIA", country_code: "ID", state: "BANTEN", city: "KAB. TANGERANG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KOTA BOGOR"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KAB. BOGOR"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KOTA BANDUNG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KAB. BANDUNG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KAB. BANDUNG BARAT"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KOTA BEKASI"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KAB. BEKASI"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA BARAT", city: "KOTA DEPOK"},
  {country: "INDONESIA", country_code: "ID", state: "DAERAH ISTIMEWA YOGYAKARTA", city: "KOTA YOGYAKARTA"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TENGAH", city: "KOTA SEMARANG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TENGAH", city: "KAB. SEMARANG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TENGAH", city: "KOTA SURAKARTA"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KOTA MALANG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KAB. MALANG"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KOTA BATU"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KOTA SURABAYA"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KAB. SIDOARJO"},
  {country: "INDONESIA", country_code: "ID", state: "JAWA TIMUR", city: "KAB. GRESIK"},
  {country: "INDONESIA", country_code: "ID", state: "BALI", city: "KOTA DENPASAR"}
].freeze
