LOCATION_SERVICES_DATA = [
  {
    service_name: "FISIOHOME_SPECIAL_TIER",
    cities: ["KOTA ADM. JAKARTA SELATAN", "KOTA ADM. JAKARTA BARAT", "KOTA ADM. JAKARTA TIMUR", "KOTA ADM. JAKARTA UTARA", "KOTA ADM. JAKARTA PUSAT", "KOTA TANGERANG SELATAN", "KAB. TANGERANG", "KOTA BEKASI", "KAB. BEKASI", "KOTA DENPASAR"]
  }
]
